// Central place for every image path on the site.
// Illustrations are generated by scripts/generate-illustrations.py into /public/images/.
// To use a photo instead, drop it in and point the path (or a pandal's image_url) at it.
// Missing files are fine: <SmartImage> hides itself and the original gradient design shows.

const slugify = (str = '') =>
  str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

// Pandal cover: its own image if set, otherwise a representative image for its category
export const pandalImage = (pandal) =>
  pandal?.image_url || `/images/pandals/category-${slugify(pandal?.category || 'community')}.jpg`;

export const routeImage = (slug) => `/images/routes/${slug}.jpg`;

export const guideImage = (slug) => `/images/guides/${slug}.jpg`;

export const MAHALAYA_IMAGE = '/images/mahalaya/mahalaya-dawn.jpg';

// Guide covers: a real photo where one fits, otherwise the guide's illustration
const GUIDE_PHOTOS = {
  'central-colony-durga-puja-2026': 'siliguri-pandal-inside',
  'mahalaya-siliguri-traditions': 'kash-sunset',
  'siliguri-pandal-hopping-guide': 'night-street',
};
export const guideCover = (slug) =>
  GUIDE_PHOTOS[slug] ? { photo: GUIDE_PHOTOS[slug] } : { src: guideImage(slug) };
